//
// Generated file, do not edit! Created by nedtool 5.6 from src/TDMAMacHeader.msg.
//

#ifndef __INET_TDMAMACHEADER_M_H
#define __INET_TDMAMACHEADER_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0506
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif


namespace inet {

class TDMAMacHeaderBase;
class TDMAMacDataFrame;
} // namespace inet

#include "inet/common/INETDefs_m.h" // import inet.common.INETDefs

#include "inet/common/packet/chunk/Chunk_m.h" // import inet.common.packet.chunk.Chunk

#include "inet/linklayer/common/MacAddress_m.h" // import inet.linklayer.common.MacAddress


namespace inet {

/**
 * Enum generated from <tt>src/TDMAMacHeader.msg:24</tt> by nedtool.
 * <pre>
 * enum TDMAMacTypes
 * {
 *     DELAY = 1;
 *     _SLOT_BEGINS = 2;
 * }
 * </pre>
 */
enum TDMAMacTypes {
    DELAY = 1,
    _SLOT_BEGINS = 2
};

/**
 * Class generated from <tt>src/TDMAMacHeader.msg:30</tt> by nedtool.
 * <pre>
 * class TDMAMacHeaderBase extends FieldsChunk
 * {
 *     MacAddress srcAddr;
 *     MacAddress destAddr;
 *     TDMAMacTypes type;
 * }
 * </pre>
 */
class TDMAMacHeaderBase : public ::inet::FieldsChunk
{
  protected:
    MacAddress srcAddr;
    MacAddress destAddr;
    inet::TDMAMacTypes type = static_cast<inet::TDMAMacTypes>(-1);

  private:
    void copy(const TDMAMacHeaderBase& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const TDMAMacHeaderBase&);

  public:
    TDMAMacHeaderBase();
    TDMAMacHeaderBase(const TDMAMacHeaderBase& other);
    virtual ~TDMAMacHeaderBase();
    TDMAMacHeaderBase& operator=(const TDMAMacHeaderBase& other);
    virtual TDMAMacHeaderBase *dup() const override {return new TDMAMacHeaderBase(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual const MacAddress& getSrcAddr() const;
    virtual MacAddress& getSrcAddrForUpdate() { handleChange();return const_cast<MacAddress&>(const_cast<TDMAMacHeaderBase*>(this)->getSrcAddr());}
    virtual void setSrcAddr(const MacAddress& srcAddr);
    virtual const MacAddress& getDestAddr() const;
    virtual MacAddress& getDestAddrForUpdate() { handleChange();return const_cast<MacAddress&>(const_cast<TDMAMacHeaderBase*>(this)->getDestAddr());}
    virtual void setDestAddr(const MacAddress& destAddr);
    virtual inet::TDMAMacTypes getType() const;
    virtual void setType(inet::TDMAMacTypes type);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const TDMAMacHeaderBase& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, TDMAMacHeaderBase& obj) {obj.parsimUnpack(b);}

/**
 * Class generated from <tt>src/TDMAMacHeader.msg:37</tt> by nedtool.
 * <pre>
 * class TDMAMacDataFrame extends TDMAMacHeaderBase
 * {
 *     int networkProtocol = -1;
 * }
 * </pre>
 */
class TDMAMacDataFrame : public ::inet::TDMAMacHeaderBase
{
  protected:
    int networkProtocol = -1;

  private:
    void copy(const TDMAMacDataFrame& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const TDMAMacDataFrame&);

  public:
    TDMAMacDataFrame();
    TDMAMacDataFrame(const TDMAMacDataFrame& other);
    virtual ~TDMAMacDataFrame();
    TDMAMacDataFrame& operator=(const TDMAMacDataFrame& other);
    virtual TDMAMacDataFrame *dup() const override {return new TDMAMacDataFrame(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual int getNetworkProtocol() const;
    virtual void setNetworkProtocol(int networkProtocol);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const TDMAMacDataFrame& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, TDMAMacDataFrame& obj) {obj.parsimUnpack(b);}

} // namespace inet

#endif // ifndef __INET_TDMAMACHEADER_M_H

